<p>This is a demo block </p>
<div id = "js-demo" data-mage-init='{"alexye_catalog_demoFunction": {} }'></div>
<div id = "js-demo" data-mage-init='{"alexye_catalog_demoFunction": {"text":"Demo text"} }'></div>
<div id = "js-demo" data-mage-init='{"alexye_catalog_demoFunction": {"text":"Demo text2"} }'></div>
<!--<script type="text/javascript">-->
<!--    require(['AlexYe_Catalog/js/demo-function'], function (demoFunction){-->
<!--        demoFunction();-->
<!--        }-->
<!--    )-->
<!---->
<!--</script>-->
