<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="alex-ye-customer-preferences-form-container" data-bind="scope: 'customerPreferencesForm'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#alex-ye-customer-preferences-form-container": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
</div>
