<?php /** @var \AlexYe\CustomerPreferences\Block\Form $block */ ?>
<div data-bind="scope: 'customerPreferencesForm'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customerPreferencesForm": {
                        "component": "alexYe_customerPreferences_form",
                        "attributes": <?= $block->getAttributesJson() ?>,
                        "action": "<?= $block->escapeUrl($block->getUrl('alex_ye_customer_preferences/preferences/save')) ?>"                    }
                }
            }
        }
    }

</script>
