<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div data-bind="scope: 'customerPreferencesForm'" style="width: 50%; margin: 0 auto;">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customerPreferencesForm": {
                    "component": "alexYe_customerPreferences_form",
                        "attributes": <?= $block->getAttributesJson() ?>
                    }
                }
            }
        }
    }
</script>
