<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div data-bind="scope: 'customerPreferencesSidebar'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customerPreferencesSidebar": {
                        "component": "alexYe_customerPreferences_sidebar"
                    }
                }
            }
        }
    }
</script>
